apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bookstore-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - customer-service
      containers:
        - name: customer-service
          image: code250/customerservice:customer
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKERS
              value: "3.129.102.184:9092,18.118.230.221:9093,3.130.6.49:9094"
            - name: KAFKA_TOPIC
              value: "rmunyema.customer.evt"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: R1ch@rd@!Munye
            - name: DB_NAME
              value: bookstore
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "3306"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
