apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-bff
  namespace: bookstore-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-bff
  template:
    metadata:
      labels:
        app: mobile-bff
    spec:
      containers:
        - name: mobile-bff
          image: code250/mobilebffservice:mobile
          imagePullPolicy: Always
          env:
            - name: CUSTOMER_BACKEND_SERVICES_BASE_URL
              value: "http://customer-service:3000"
            - name: BOOK_COMMAND_SERVICES_BASE_URL
              value: "http://book-command:3000"
            - name: BOOK_QUERY_SERVICES_BASE_URL
              value: "http://book-query:3000"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
